# Generated by Django 6.0 on 2025-12-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('Linguagem', 'Linguagem'), ('Framework', 'Framework'), ('Servico Cloud', 'Serviço Cloud'), ('Banco de Dados', 'Banco de Dados'), ('Outro', 'Outro')], max_length=50)),
                ('versao', models.CharField(blank=True, max_length=50, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
