# Generated by Django 6.0 on 2025-12-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
        ('tecnologia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planejado', 'Planejado'), ('Em Execução', 'Em Execução'), ('Concluido', 'Concluído'), ('Cancelado', 'Cancelado')], default='Planejado', max_length=50)),
                ('risco', models.CharField(choices=[('Baixo', 'Baixo'), ('Medio', 'Médio'), ('Alto', 'Alto'), ('Critico', 'Crítico')], default='Baixo', max_length=50, verbose_name='Nível de Risco')),
                ('orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Orçamento (R$)')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='departamento.departamento')),
                ('tecnologias', models.ManyToManyField(related_name='projetos', to='tecnologia.tecnologia')),
            ],
        ),
    ]
